name: dbt_project
config-version: 2
version: 1.0
profile: dbt_oracle_test

quoting:
    database: false
    identifier: false
    schema: false

on-run-start:
    - "select 'hook start' from dual"

on-run-end:
    - "select 'hook ended' from dual"
