dbt_oracle_test:
    target: dev
    outputs:
        dev:
            type: oracle
            user: dbt_test
            pass: dbt_test
            dbname: xe
            schema: dbt_test_out
            threads: 4
            debug_log_commands: True
            cursor_precode: "select 1 as abc from dual"
